import type { ShowcaseSite, SiteLayout, SitePalette, SitePattern, SiteTypeface } from '$lib/site-types';

type SiteSeed = readonly [
	slug: string,
	name: string,
	category: string,
	tagline: string,
	description: string,
	eyebrow: string,
	cta: string,
	secondary: string
];

const seeds: SiteSeed[] = [
	['lumen-quantum', 'Lumen Quantum', 'Deep Tech', 'Computing beyond certainty.', 'A quantum computing laboratory turning probabilistic research into practical infrastructure.', 'Quantum systems · 2026', 'Enter the lab', 'Read the research'],
	['form-haus', 'Form Haus', 'Architecture', 'Space, reduced to its essence.', 'A Copenhagen practice creating monumental spaces with a disciplined, deeply human point of view.', 'Architecture · Copenhagen', 'View projects', 'Studio profile'],
	['aera-skin', 'Aera Skin', 'Beauty', 'Your skin, in a softer light.', 'Barrier-first skincare balancing clinical clarity, tactile ritual, and a quieter kind of luxury.', 'Barrier-first skincare', 'Shop the ritual', 'Take the skin quiz'],
	['void-unit', 'Void Unit', 'Streetwear', 'Uniforms for the after-hours.', 'A raw, uncompromising streetwear label making limited systems for life beyond the nine-to-five.', 'Drop 07 · No restock', 'Shop the drop', 'View lookbook'],
	['ember-field', 'Ember & Field', 'Coffee', 'Roasted slowly. Remembered vividly.', 'Seasonal coffee traced from highland farms to small-batch roasts and the rituals they become.', 'Small-batch coffee', 'Find your roast', 'Meet the producers'],
	['selene-mission', 'Selene Mission', 'Aerospace', 'The moon is our next address.', 'A private lunar program preparing its first autonomous surface habitat and a new chapter off-world.', 'Lunar habitat · M01', 'Track the mission', 'Explore the vehicle'],
	['blue-hour-club', 'Blue Hour Club', 'Jazz', 'The city sounds better after midnight.', 'A Chicago room for searching sets, resident artists, low light, and conversations that run late.', 'Live in Chicago', "See tonight's set", 'Reserve a table'],
	['northstar-money', 'Northstar', 'Fintech', 'A clearer way to grow wealth.', 'Personal finance guidance that balances confident long-term planning with precise, useful data.', 'Investing, simplified', 'Build your plan', 'See how it works'],
	['mosslight', 'Mosslight', 'Hospitality', 'Disappear into the green.', 'Restorative forest cabins, seasonal field notes, and unhurried itineraries in the Cascades.', 'Cabins in the Cascades', 'Plan your stay', 'Explore the grounds'],
	['frame-zero', 'Frame Zero', 'Cinema', 'Films that refuse the expected.', 'A living festival program for independent films, sharp new voices, and stories without a formula.', 'Independent cinema', 'Start watching', 'Browse the program'],
	['wild-culture', 'Wild Culture', 'Food', 'Good things take time.', 'A playful fermentation studio making live cultures, seasonal pantry goods, and hands-on workshops.', 'Fermented in Brooklyn', 'Open the pantry', 'Book a workshop'],
	['maison-nocturne', 'Maison Nocturne', 'Fashion', 'Tailored for the hours unseen.', 'A Paris atelier shaping sculptural silhouettes with nocturnal restraint and exacting craft.', 'Collection XII · Paris', 'Discover the collection', 'Enter the atelier'],
	['kinetic-foundry', 'Kinetic Foundry', 'Robotics', 'Machines with a human sense of motion.', 'Dexterous robotic systems designed around useful movement, adaptable tools, and safer work.', 'Applied robotics', 'Meet the machines', 'View capabilities'],
	['tideline-supply', 'Tideline Supply', 'Surf', 'Made for water without walls.', 'Durable coastal goods and field-tested layers shaped by remote breaks and long days outside.', 'Pacific field goods', 'Shop the coast', 'Read field notes'],
	['glyph-dept', 'Glyph Department', 'Typography', 'Typefaces with something to say.', 'An independent foundry where variable letters stretch, collide, and perform across every screen.', 'Independent type foundry', 'Test the type', 'Browse families'],
	['one-point-five', 'One Point Five', 'Climate', 'Make the future measurable.', 'A climate observatory turning dense planetary signals into urgent, legible, collective action.', 'Climate data observatory', 'Explore the signals', 'Read the outlook'],
	['oro-still', 'Oro Still', 'Jewelry', 'Objects for your private mythology.', 'Hand-cast jewelry made in Florence and presented as intimate artifacts to carry for a lifetime.', 'Handmade in Florence', 'View the objects', 'Our materials'],
	['static-bloom', 'Static Bloom', 'Music', 'Beautiful noise, carefully released.', 'A fiercely independent label releasing chromatic records, artist stories, and limited vinyl editions.', 'Records · Editions · Noise', 'Hear the latest', 'Visit the archive'],
	['peloton-north', 'Peloton North', 'Cycling', 'Take the longer road.', 'An Oslo cycling collective pairing exploratory routes, precise technical apparel, and weekly rides.', 'Ride club · Oslo', 'Join the next ride', 'Explore routes'],
	['latent-garden', 'Latent Garden', 'AI Research', 'Intelligence should feel alive.', 'An optimistic research studio exploring creative models through organic simulations and open essays.', 'Creative intelligence', 'Explore experiments', 'Read our papers'],
	['crumb-theory', 'Crumb Theory', 'Bakery', 'A daily study in butter and flour.', "A neighborhood bakery sharing today's counter, preorder specials, and obsessive pastry notes.", 'Baked each morning', "See today's counter", 'Preorder a box'],
	['museum-small-things', 'Museum of Small Things', 'Culture', 'Ordinary objects. Extraordinary stories.', 'A digital museum revealing the emotional histories hidden inside the things people keep.', 'Open collection · 4,208 objects', 'Browse the collection', 'Submit an object'],
	['plane-object', 'Plane Object', 'Furniture', 'Furniture with nothing to hide.', 'Modular objects with honest materials, flat-pack ingenuity, and endlessly adaptable forms.', 'Objects for modern rooms', 'Configure a piece', 'View the system'],
	['afterlight-arcade', 'Afterlight Arcade', 'Gaming', 'One more run before sunrise.', 'A neon-soaked arcade of original worlds, weekly challenges, and a living global leaderboard.', 'Independent games universe', 'Press start', 'View leaderboards'],
	['stillroom', 'Stillroom', 'Wellness', 'A quieter place inside your day.', 'Gentle breathwork and meditation practices made around spacious pacing and responsive ambient form.', 'Daily practices for calm', 'Begin a session', 'Explore practices'],
	['low-sun-spirits', 'Low Sun Spirits', 'Beverage', 'Distilled at the edge of daylight.', 'Small-batch spirits rooted in desert botanicals, long shadows, and patient experimentation.', 'Desert botanical spirits', 'Discover the bottles', 'Visit the distillery'],
	['soft-earth-studio', 'Soft Earth Studio', 'Ceramics', 'Made slowly enough to keep the fingerprints.', 'Imperfect vessels, studio rituals, and the landscapes held inside every glaze.', 'Hand-thrown ceramics', 'View available work', 'Visit the studio'],
	['relay-global', 'Relay Global', 'Logistics', 'Every shipment, perfectly in motion.', 'A connected freight network making global routes, handoffs, and operations clear in real time.', 'Connected freight network', 'Track a shipment', 'Explore the network'],
	['perigee-house', 'Perigee House', 'Space Hotel', 'Earth has never looked this good.', 'A speculative orbital hotel pairing aerospace precision with five-star perspective.', 'Low-Earth orbit · 2031', 'Reserve your orbit', 'Tour the station'],
	['common-blue', 'Common Blue', 'Nonprofit', 'The ocean belongs to everyone.', 'A coastal action network connecting restoration projects, field data, and local volunteers.', 'Coastal action network', 'Join a local project', 'See our impact'],
	['meridian-works', 'Meridian Works', 'Watchmaking', 'Time, engineered into character.', 'Independent watches built around precise movements, enduring materials, and patient assembly.', 'Independent watchmaking', 'Explore the collection', 'See the movement'],
	['odd-common', 'Odd Common', 'Creative Agency', 'Make the familiar impossible to ignore.', 'An independent practice making bold identities, playful campaigns, and useful digital worlds.', 'Independent creative practice', 'See selected work', 'Start a project'],
	['margin-quarterly', 'Margin Quarterly', 'Publishing', 'Ideas worth leaving room for.', 'A longform journal pairing cultural criticism with generous typography and collectible editions.', 'Issue 18 · The distance between', 'Read the new issue', 'Browse the archive'],
	['solar-flare-fest', 'Solar Flare', 'Festival', 'Three nights. No small feelings.', 'A kinetic desert gathering of future-facing music, radiant art, and nights without edges.', 'Joshua Tree · Sep 18–20', 'Get festival passes', 'Explore the lineup'],
	['atlas-noir', 'Atlas Noir', 'Luxury Travel', 'Go where the map ends.', 'Private expeditions shaped around remote landscapes, rare access, and impeccable restraint.', 'Bespoke journeys', 'Plan an expedition', 'View field journal'],
	['bloom-biotech', 'Bloom', 'Biotechnology', 'Medicine, grown differently.', 'Regenerative therapies engineered from cells, fungi, and the surprising intelligence of plants.', 'Biology in motion', 'Explore the science', 'Meet the platform'],
	['signal-house', 'Signal House', 'Creative Agency', 'Make noise worth hearing.', 'A culture-first studio building identities, campaigns, and digital worlds for ambitious brands.', 'Independent creative studio', 'See selected work', 'Start a project'],
	['common-thread', 'Common Thread', 'Sustainable Fashion', 'Clothes with a longer story.', 'Seasonless essentials made transparently from traceable fibers and designed to be repaired.', 'Edition 04', 'Shop the collection', 'Trace our materials'],
	['lumen-clinic', 'Lumen Clinic', 'Preventive Health', 'A clearer view of your health.', 'Membership diagnostics that turn complex health signals into calm, actionable guidance.', 'Preventive care, redesigned', 'Join Lumen', 'How it works'],
	['paper-moon', 'Paper Moon', 'Independent Cinema', 'Films that linger.', 'A repertory cinema for overlooked classics, midnight oddities, and unforgettable new voices.', 'Tonight at Paper Moon', 'Get tickets', 'Browse the archive'],
	['orbit-bank', 'Orbit', 'Fintech', 'Money that moves with you.', 'One beautifully simple account for saving, spending, investing, and living across borders.', 'Banking without gravity', 'Open an account', 'See benefits'],
	['field-notes', 'Field Notes', 'Architecture', 'Buildings that belong.', 'A landscape-led practice creating low-impact homes, retreats, and generous public spaces.', 'Architecture in context', 'View projects', 'Read our approach'],
	['vanta-audio', 'Vanta Audio', 'Consumer Audio', 'Hear the space between.', 'Reference headphones tuned for depth, texture, and the emotional weight of sound.', 'Series One', 'Listen closer', 'Explore the engineering'],
	['sunday-supper', 'Sunday Supper', 'Restaurant', 'Come hungry. Stay awhile.', 'A neighborhood table serving generous seasonal plates, natural wine, and unhurried evenings.', 'Dinner from five', 'Book a table', "See tonight's menu"],
	['kinetic-type', 'Kinetic Type', 'Type Foundry', 'Letters made to move.', 'Experimental typefaces for screens, identities, motion systems, and formats still to come.', 'Independent type foundry', 'Browse typefaces', 'Try the variable lab'],
	['moss-works', 'Moss Works', 'Landscape Design', 'Let the wild back in.', 'Ecological gardens and living landscapes that support biodiversity while making room for people.', 'Gardens for the future', 'Explore our landscapes', 'Planting philosophy'],
	['afterimage-digital', 'Afterimage Digital', 'Digital Art', 'Art beyond the frame.', 'An online gallery commissioning luminous interactive work from artists shaping digital culture.', 'Exhibition 017', 'Enter the exhibition', 'Meet the artists'],
	['quiet-mile', 'Quiet Mile', 'Electric Mobility', 'The city, softened.', 'Silent, lightweight electric bikes made for elegant movement through dense urban life.', 'Urban electric mobility', 'Meet the M1', 'Book a test ride'],
	['relic', 'Relic', 'Vintage Marketplace', 'Objects worth keeping.', 'A curated market for enduring furniture, rare design, and beautifully weathered everyday things.', 'Newly unearthed', 'Browse the collection', 'Sell an object'],
	['lucid-learning', 'Lucid', 'Education', 'Learn by seeing.', 'Interactive courses turn difficult ideas into playful simulations, diagrams, and experiments.', 'Ideas you can touch', 'Start exploring', 'Browse subjects'],
	['thermal', 'Thermal', 'Climate Technology', 'Heat, put to work.', 'Industrial systems capture wasted heat and return it as clean, reliable energy.', 'Closing the energy loop', 'See the technology', 'Read the impact report'],
	['tiny-giants', 'Tiny Giants', "Children's Museum", 'Big wonder for little minds.', 'A hands-on museum where children build worlds, chase questions, and make magnificent messes.', 'Now playing', 'Plan your visit', "See today's activities"],
	['carbon-zero', 'Carbon Zero', 'Carbon Accounting', 'Make every tonne visible.', 'Emissions intelligence for teams ready to turn climate promises into measurable progress.', 'Operational carbon intelligence', 'Measure your footprint', 'View methodology'],
	['nocturne', 'Nocturne', 'Fragrance', 'Scent after dark.', 'Perfumes composed from smoke, mineral, night-blooming flowers, and distant weather.', 'Parfums de nuit', 'Discover the collection', 'Find your scent'],
	['civic-stack', 'Civic Stack', 'Public Technology', 'Better tools for public life.', 'Open infrastructure helping local governments deliver clear, accessible digital services.', 'Technology for everyone', 'Explore the platform', 'Read case studies'],
	['soft-power', 'Soft Power', 'Culture Magazine', 'The ideas shaping how we live.', 'Independent reporting on taste, influence, design, identity, and the forces behind culture.', 'Issue No. 12', 'Read the latest issue', 'Browse the archive'],
	['rare-earth', 'Rare Earth', 'Jewelry', 'Formed by pressure.', 'Sculptural jewelry made with recycled metals, traceable stones, and an instinct for imperfection.', 'Objects of permanence', 'View the collection', 'Our materials'],
	['folkways', 'Folkways', 'Music Archive', 'Every song carries a place.', 'A living archive of field recordings, oral histories, and traditional music from across the world.', 'Sounds from the archive', 'Start listening', 'Explore the map'],
	['monolith-security', 'Monolith Security', 'Cybersecurity', 'Nothing gets through.', 'Adaptive infrastructure protecting critical systems without slowing the people who run them.', 'Zero-trust infrastructure', 'Secure your stack', 'View threat research'],
	['salt-air', 'Salt Air', 'Coastal Hotel', 'Stay close to the tide.', 'A quiet inn shaped by open windows, local food, weathered timber, and slow mornings.', 'Rooms by the sea', 'Book your stay', 'Explore the coast'],
	['wavelength', 'Wavelength', 'Marine Research', 'Listen to the ocean change.', 'Open acoustic sensing helps researchers understand and protect marine ecosystems.', 'Ocean intelligence', 'Dive into the data', 'Hear live recordings'],
	['paprika', 'Paprika', 'Food Delivery', 'Dinner should feel alive.', 'Bold chef-made meals from independent kitchens, delivered hot and ready for the table.', 'Made nearby', "Find tonight's dinner", 'Meet the kitchens'],
	['slow-form', 'Slow Form', 'Furniture', 'Made at the speed of care.', 'Numbered furniture shaped from local timber and designed to gather character over decades.', 'Furniture for keeping', 'View the collection', 'Visit the workshop'],
	['deep-time', 'Deep Time', 'Natural History', 'Four billion years, still unfolding.', 'An immersive museum tracing the improbable story of Earth through fossils, climates, and extinction.', 'An atlas of Earth', 'Begin the timeline', 'Explore the collection'],
	['pixel-garden', 'Pixel Garden', 'Indie Games', 'Small worlds. Strange rules.', 'A tiny studio growing playful, atmospheric worlds for curious players of every age.', 'Independent game studio', 'Play our worlds', 'Meet the studio'],
	['alto', 'Alto', 'Workspace', 'Room for your best thinking.', 'Flexible studios, quiet rooms, and thoughtful hospitality for independent people and small teams.', 'A better place to work', 'Find a space', 'Explore membership'],
	['future-archive', 'Future Archive', 'Digital Preservation', 'Save what tomorrow should remember.', 'Long-term preservation for digital art, cultural records, and the fragile history made online.', 'Memory infrastructure', 'Explore the archive', 'Preserve a collection'],
	['lumen-ark', 'Lumen Ark', 'Architecture', 'Buildings shaped by light.', 'A Copenhagen studio creating quiet, daylight-led spaces for culture and living.', 'Architecture / Copenhagen', 'Explore projects', 'Studio notes'],
	['moss-matter', 'Moss & Matter', 'Biomaterials', 'Materials that return to earth.', 'Packaging, textiles, and interiors grown from mycelium and agricultural waste.', 'Grown, not manufactured', 'Meet the materials', 'View field journal'],
	['nightjar-fm', 'Nightjar FM', 'Independent Radio', 'Broadcasts after dark.', 'Independent transmissions of ambient, experimental, and left-field music through the night.', 'Live from 11:00 PM', 'Listen live', 'Browse schedule'],
	['heliograph-energy', 'Heliograph', 'Solar Energy', 'Power, beautifully placed.', 'Elegant solar infrastructure designed for homes, campuses, and public space.', 'Solar infrastructure / 2026', 'Plan your system', 'See installations'],
	['velvet-orbit', 'Velvet Orbit', 'Fashion', 'Dress for another gravity.', 'A directional label pairing sculptural tailoring with liquid metallic textiles.', 'Collection 04 / Aphelion', 'Enter collection', 'View campaign'],
	['kintsu-care', 'Kintsu', 'Mental Wellness', 'Care for the life between appointments.', 'A calm platform connecting daily reflection, therapy, and practical mental health tools.', 'Whole-person mental care', 'Begin a check-in', 'How it works'],
	['raster-rush', 'Raster Rush', 'Game Studio', 'Tiny pixels. Huge worlds.', 'An indie studio building kinetic arcade worlds with tactile mechanics and loud color.', 'Insert imagination', 'Play the demo', 'Meet the crew'],
	['paloma-kitchen', 'Paloma', 'Restaurant', 'Wood fire, citrus, late nights.', 'A neighborhood kitchen serving coastal plates, mezcal, and warm evenings around the fire.', 'Mexico City / Roma Norte', 'Book a table', "See tonight's menu"],
	['afterimage-archive', 'Afterimage Archive', 'Photography Archive', 'What remains after looking.', 'A digital archive preserving overlooked experimental photography from 1968 to 1999.', 'Archive 001—947', 'Browse the archive', 'Read curatorial note'],
	['tidepool-lab', 'Tidepool Lab', 'Ocean Research', 'Reading the edge of the sea.', 'A field station mapping biodiversity, temperature shifts, and resilient marine habitats.', 'Field note / 37.7749° N', 'Dive into the data', 'Meet the researchers'],
	['narra', 'Narra', 'Knowledge Technology', 'Turn research into a living story.', 'A collaborative workspace connecting sources, notes, and ideas into clear narrative maps.', 'Context, connected', 'Build a narrative', 'Watch overview'],
	['offgrid-works', 'Offgrid Works', 'Adventure Vehicles', 'A cabin with a steering wheel.', 'Modular electric campers engineered for quiet roads, remote work, and weekends beyond signal.', 'Built beyond the map', 'Configure yours', 'Take the tour'],
	['sonnet-ceramics', 'Sonnet Ceramics', 'Craft', 'Objects for slower rooms.', 'Small-batch vessels and tableware shaped by hand in a light-filled coastal studio.', 'Made in small editions', 'Shop the collection', 'Visit the studio'],
	['zero-hour', 'Zero Hour', 'Climate Journalism', 'The climate story, without distance.', 'Independent reporting through investigations, local voices, and visual evidence.', 'Reporting from the threshold', 'Read the latest', 'Explore the atlas'],
	['chorus-room', 'Chorus Room', 'Social Music', 'Listening is better together.', 'Live album rooms where friends trade discoveries and talk between tracks.', '12,408 listeners online', 'Join a room', 'Start a session'],
	['veldt-parfums', 'Veldt Parfums', 'Fragrance', 'Landscapes, bottled.', 'Botanical compositions inspired by dry grasslands, mineral rain, and distant smoke.', 'Olfactory landscape No. 06', 'Discover the scents', 'Read the field notes'],
	['court-eleven', 'Court Eleven', 'Tennis Club', 'New rituals for the old game.', 'A design-led city club combining open play, coaching, recovery, and all-day hospitality.', 'Brooklyn / Open 06:00', 'Book a court', 'Join the club'],
	['monolith-shield', 'Monolith Shield', 'Cybersecurity', 'Know what touches your systems.', 'Continuous security maps exposure, verifies controls, and responds at machine speed.', 'Security posture / Live', 'Run an assessment', 'View threat brief'],
	['paper-plane', 'Paper Plane', 'Travel Journal', 'Go somewhere worth writing down.', 'A slow-travel journal publishing intimate city guides, train routes, and stories from the road.', 'Dispatch No. 28 / Tbilisi', 'Read the dispatch', 'Open the map'],
	['bloomline', 'Bloomline', 'Floral Design', 'Flowers with a point of view.', 'Sculptural floral compositions for homes, gatherings, galleries, and unexpected Tuesdays.', 'Seasonal stems / London', 'Send flowers', 'View installations'],
	['transit-2050', 'Transit 2050', 'Urban Mobility', 'The city moves when everyone can.', 'A public initiative visualizing faster, cleaner, and more equitable urban transportation.', 'A mobility plan for everyone', 'Explore the network', 'Read the proposal'],
	['fondue-club', 'Fondue Club', 'Supper Club', 'Dip irresponsibly.', 'A roving supper club serving bubbling cheese, cold wine, and very unserious evenings.', 'Next melt / Friday 8 PM', 'Grab a seat', 'Inspect the menu'],
	['null-laboratory', 'NULL Laboratory', 'Experimental Tech', 'Prototypes for uncertain futures.', 'Research into spatial computing, machine perception, and delightfully strange interfaces.', 'Research index / 0090', 'Open experiments', 'Read the manifesto'],
	['aurora-field', 'Aurora Field', 'Astronomy', 'A darker sky. A clearer universe.', 'A remote observatory offering research residencies and public nights under northern skies.', 'Latitude 64.1466° N', "See tonight's sky", 'Plan a visit'],
	['crumb-society', 'Crumb Society', 'Bakery', 'Loud pastry. Quiet mornings.', 'Heritage grain, cultured butter, and seasonal fruit laminated into daily rituals.', 'Fresh from 7:00', "See today's bake", 'Order a box'],
	['latent-gallery', 'Latent Gallery', 'Generative Art', 'Art that never repeats itself.', 'A digital gallery presenting algorithmic editions, living systems, and machine-assisted practices.', 'Exhibition 13 / Emergence', 'Enter exhibition', 'Meet the artists'],
	['fellowship-fund', 'Fellowship', 'Venture Studio', 'Back the beautifully unreasonable.', 'An early-stage fund for technical founders building ambitious tools for the physical world.', 'Pre-seed / Deep systems', 'Meet the portfolio', 'Pitch the partnership'],
	['milkweed-school', 'Milkweed School', 'Outdoor Education', 'Let curiosity get muddy.', 'A forest learning community where children explore ecology, craft, movement, and seasonal change.', 'Learning outside / Ages 4–11', 'Explore the school', 'Book an open day'],
	['kiln-coffee', 'Kiln Coffee', 'Coffee Roastery', 'Heat reveals character.', 'Expressive coffees sourced carefully and developed with patient, exact roast profiles.', 'Roasted this week / Batch 214', 'Shop fresh coffee', 'Meet the producers'],
	['agora-index', 'Agora Index', 'Civic Data', 'Public life, made legible.', 'An open dashboard translating budgets, housing, transit, and participation into local signals.', 'City pulse / Updated hourly', 'Explore your city', 'Download open data'],
	['drift-sleep', 'Drift', 'Sleep Technology', 'A softer landing for your day.', 'An adaptive sleep companion combining sound, breath, and gentle screen-free routines.', 'Tonight begins here', 'Start winding down', 'Hear a soundscape'],
	['relay-robotics', 'Relay Robotics', 'Robotics', 'Robots that work the room.', 'Friendly autonomous robots handling indoor logistics across hospitals, hotels, and campuses.', 'Autonomy for everyday spaces', 'Meet Relay One', 'Watch it work'],
	['finale-future', 'Finale', 'Digital Culture', 'One hundred visions. One strange future.', 'Three days of digital art, sound, code, performance, and conversations beyond the interface.', 'October 08–10 / Everywhere', 'Enter the festival', 'View the program']
];

const layouts: SiteLayout[] = ['split', 'centered', 'editorial', 'poster', 'catalog', 'dashboard', 'cinematic', 'brutalist', 'luxury', 'orbital'];
const patterns: SitePattern[] = ['mesh', 'grid', 'rings', 'stripes', 'dots', 'sun', 'checker', 'aurora', 'blocks', 'halo', 'noise', 'waves', 'type'];
const typefaces: SiteTypeface[] = ['grotesk', 'serif', 'mono', 'rounded', 'condensed', 'display', 'humanist'];

const palettes: SitePalette[] = [
	{ bg: '#070A12', ink: '#F1F5FF', accent: '#7C5CFF', accent2: '#3CF2C7', muted: '#78839F' },
	{ bg: '#EEEDE8', ink: '#171714', accent: '#E3492F', accent2: '#9DA58B', muted: '#6D706A' },
	{ bg: '#F7F1EC', ink: '#382D2A', accent: '#D49B8E', accent2: '#B8C8B3', muted: '#8D7D77' },
	{ bg: '#E9FF36', ink: '#0A0A0A', accent: '#FF3D00', accent2: '#6C43FF', muted: '#575D20' },
	{ bg: '#271B16', ink: '#F6E7D2', accent: '#E36F3A', accent2: '#C7A45E', muted: '#A6907A' },
	{ bg: '#04070B', ink: '#E7F2F8', accent: '#FFB000', accent2: '#78D7FF', muted: '#76909D' },
	{ bg: '#10152B', ink: '#F9EED7', accent: '#EF476F', accent2: '#55C1FF', muted: '#8F8DA1' },
	{ bg: '#F3F7F2', ink: '#13251F', accent: '#21A179', accent2: '#FFCB66', muted: '#6A7C76' },
	{ bg: '#18231B', ink: '#EDF0DF', accent: '#A6C36F', accent2: '#D8A15D', muted: '#87907B' },
	{ bg: '#0B0B0B', ink: '#F4F1E8', accent: '#FF4D4D', accent2: '#B7A6FF', muted: '#8D8982' },
	{ bg: '#FFF4CC', ink: '#27231D', accent: '#FF6542', accent2: '#70B77E', muted: '#746C55' },
	{ bg: '#130F12', ink: '#F2E9E4', accent: '#A66378', accent2: '#C9A96E', muted: '#8E8185' },
	{ bg: '#E8ECEF', ink: '#13191D', accent: '#F05A28', accent2: '#2176FF', muted: '#687178' },
	{ bg: '#E7DCC8', ink: '#17313B', accent: '#E9794A', accent2: '#4D9D9A', muted: '#6E7C7C' },
	{ bg: '#F5F2EA', ink: '#111111', accent: '#2457FF', accent2: '#FF5CA8', muted: '#74716B' },
	{ bg: '#061E24', ink: '#E7FBF7', accent: '#48D6A8', accent2: '#F4D35E', muted: '#77A099' },
	{ bg: '#F0E9DF', ink: '#28211F', accent: '#B8893E', accent2: '#795663', muted: '#7C7069' },
	{ bg: '#1B0826', ink: '#FFF6DB', accent: '#FF3CAC', accent2: '#62F6FF', muted: '#9A859F' },
	{ bg: '#DDE7E1', ink: '#15241D', accent: '#F04F38', accent2: '#2855D9', muted: '#697A72' },
	{ bg: '#F1FFE8', ink: '#172514', accent: '#8B5CF6', accent2: '#31C48D', muted: '#6D8065' },
	{ bg: '#FFF0D8', ink: '#4A2921', accent: '#F28C28', accent2: '#E45D75', muted: '#866B5E' },
	{ bg: '#EAE7DF', ink: '#24201B', accent: '#D94F4F', accent2: '#427AA1', muted: '#716D66' },
	{ bg: '#080515', ink: '#F8F4FF', accent: '#00F5D4', accent2: '#FF2E88', muted: '#8B829E' },
	{ bg: '#E8F0EF', ink: '#263837', accent: '#8E9AAF', accent2: '#D7A9A0', muted: '#788786' },
	{ bg: '#2A0845', ink: '#FFF3D1', accent: '#FF7A00', accent2: '#F72585', muted: '#9E7EA7' }
];

export const sites: ShowcaseSite[] = seeds.map((seed, index) => ({
	id: index + 1,
	slug: seed[0],
	name: seed[1],
	category: seed[2],
	tagline: seed[3],
	description: seed[4],
	eyebrow: seed[5],
	cta: seed[6],
	secondary: seed[7],
	layout: layouts[index % layouts.length],
	pattern: patterns[(index * 7 + 3) % patterns.length],
	typeface: typefaces[(index * 5 + 2) % typefaces.length],
	palette: palettes[(index * 7) % palettes.length]
}));

export const siteBySlug = new Map(sites.map((site) => [site.slug, site]));
